services:
  - type: web
    name: m-esakafo
    env: php
    plan: free
    runtime: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-interaction --optimize-autoloader --no-dev
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
    buildFilter:
      paths:
        - composer.json
        - composer.lock
        - config/**
        - public/**
        - src/**
        - templates/**
        - vendor/**